### ISSUE TITLE
Setting up a Yocto build with Qt5 for Raspberry Pi 2/3 with official touchscreen

### ISSUE THREAD

**Issue by gsayes** [erikboto/meta-erborpi#1]
Hi Erik,
I wanted to thank you for the great yocto qt blog at http://blog.unixshell.se/?p=27. The steps used there work till about a week or so ago. the old image i have booted perfectly. I have learned a great deal about yocto and bitbake recipes in the past few days thanks to your blog.  I am able to add all needed modules to my build using IMAGE_INSTALL += " " placed in the rpi-build/conf/bblayers.conf. The result bitbake image has all i need and i can load it using centos 7 no issues. but when i try to use it for the raspi it hangs at the 4 raspberries. If i enable logging using the below as my cmdline.txt: "dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 loglevel=0 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait logo.nologo" it boots and i get a read only prompt so i run "mount -o remount /" and im allowed write to the file system. i can see "systemd" files make it to /bin/systemd/system/... but systemctl is not found on the disk. some how the boot script is broken. not sure why and how. some how the image is corrupt...  im still a newbie after 6 years of working with linux i have much to learn.

Any ideas on how to fix? 
Thanks,
gsayes

**Comment by erikboto** [comment]
Hi!

Which branches are you using for the meta-layers? I've done some updates to the morty release of Yocto, see http://blog.unixshell.se/?p=27#comment-367. If you are using this let me know and I'll try it out to see if I can reproduce your issues! 

Cheers,
Erik

**Comment by erikboto** [comment]
Any news?

**Comment by MaxMagazin** [comment]
Hello, http://blog.unixshell.se/?p=27 is not available (Error establishing a database connection). Is there any other place, where I could find your blog post?
